export enum JobType {
  EMAIL_NOTIFICATION = 'EMAIL_NOTIFICATION',
  DATA_EXPORT = 'DATA_EXPORT',
  IMAGE_PROCESSING = 'IMAGE_PROCESSING',
  REPORT_GENERATION = 'REPORT_GENERATION',
  DATABASE_BACKUP = 'DATABASE_BACKUP',
  CUSTOM = 'CUSTOM',
}
